### ISSUE TITLE
Issue when binding clicks

### ISSUE THREAD

**Issue by kirkbushell** [spatie/vue-pjax#1]
Currently getting the following error:

Uncaught TypeError: _vue2.default.http is not a function

This happens once the PJAX setup is complete and I click a link.

**Comment by sebastiandedeyne** [comment]
Is `vue-resource` installed and available?

(small disclaimer: this package is still in alpha)

**Comment by kirkbushell** [comment]
haha yeah I know, but we sorely need it.

Yeah it's installed and available.

Also I found your dependencies had a clash - if you install the most recent vue-resource for example, you get dependency issues.

**Comment by sebastiandedeyne** [comment]
Looks like the latest vue-resource has some breaking changes, I'll try to bump the version later today or tomorrow if I can find some time (PR welcome if it's urgent), will definitely solve the dependency issue, and I there's a slight chance the original issue is related.

**Comment by kirkbushell** [comment]
Awesome, thank you so much.

I can help contribute if you like - this package is pretty important to us and if it's not maintained we'll just take it over anyway (that's how much we need it for our setup).

**Comment by sebastiandedeyne** [comment]
I just published v0.2.0 with updated dependencies, let me know what it gives.

My plan for this package is to extract the pjax functionality to make it Vue-agnostic, and then have this one depend on it. Just haven't had the time to get it done yet.

**Comment by kirkbushell** [comment]
Unfortunately this is still busted (same error). I'm not sure why but it's unable to find http:

Uncaught TypeError: _vue2.default.http is not a function

I'll do some digging today and see if I an work it out and provide a PR.

**Comment by kirkbushell** [comment]
Further investigation points at a local configuration problem. For some reason, despite installing - vue-resource doesn't appear to be available to my application.

Ie. trying to set http configuration options simply fails - it's just not available =\
