### ISSUE TITLE
Clicked links should update the window URL bar

### ISSUE THREAD

**Issue by kirkbushell** [spatie/vue-pjax#2]
I've got the pjax setup working fine now, and it appears to be working quite well.

However, it should update the URL with the link you've just clicked, so that if someone goes back to that location, the full page is rendered.

**Comment by incraigulous** [comment]
Yo @kirkbushell, 

I found a really simple workaround. Pjax dispatches a 'pjax-replace' event that you can listen for in your main vue component. Here's an example: 

```
new Vue({
    mixins: [pjax],
    events: {
        /**
         * Update the url and replace the title when pjax loads new content.
         * @param url
         * @param content
         * @param element
         * @returns {boolean}
         */
        'pjax-replace': function({url, content, element}) {
            let title = $(content).first()
            window.history.pushState(null, title, url)
            $('title').html(title)
            return true;
        }
    }
}).$mount('body')
```

**Comment by kirkbushell** [comment]
@incraigulous we ended up having to go a different route - basically our vue js instance gets recreated every time PJAX response is returned, thereby scanning the dom.etc. for requirements as needed.
